name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
  name: Deploy to VPS
  runs-on: ubuntu-22.04
  steps:
    - name: Deploy
    uses: appleboy/ssh-action@v0.1.8
    with:
      host: 185.254.207.144
      port: 2222
      username: gaston
      key: ${{secrets.PRIVATE_KEY}}
      script: "cd /var/www/html/laravel; git pull origin main; npm run build"
